apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: slackube
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs: ["get","list","patch"]
  - apiGroups:
      - ""
    resources:
      - events
    verbs: ["list"]
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs: ["get"]
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs: [ "get", "list" ]