apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: slackube
rules:
  - apiGroups: [ "extensions", "apps" ]
    resources: [ "deployments" , "namespaces", "pods","services" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]